apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-ingress
spec:
  rules:
  - host: nexus.kubenetes.beagledata.local
    http:
      paths:
      - path: /
        backend:
          serviceName: nexus3
          servicePort: 80

