apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-scripts
data:
  entrypoint: |
    #!/bin/bash

    set -xe

    cp /scripts/config.toml /etc/gitlab-runner/

    # Register the runner
    /entrypoint register --non-interactive \
      --url http://gitlab.beagledata.com/ci \
      --executor kubernetes \
      --kubernetes-privileged=true

    # Start the runner
    /entrypoint run --user=gitlab-runner \
      --working-directory=/home/gitlab-runner
  config.toml: |
    concurrent = 10
    check_interval = 1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitlab-runner-docker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: docker-runner
        app: gitlab-runner
    spec:
      containers:
      - name: gitlab-runner-docker
        image: 172.16.210.101/public/gitlab/gitlab-runner:alpine-v9.4.2
        command: ["/bin/bash", "/scripts/entrypoint"]
        imagePullPolicy: IfNotPresent
        env:
        - name: REGISTRATION_TOKEN
          value: "P9HBJsEY11az3isEy5yp"
        resources:
          limits:
            memory: 500Mi
            cpu: 600m
          requests:
            memory: 500Mi
            cpu: 600m
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        - name: var-run-docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: var-run-docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: scripts
        configMap:
          name: gitlab-runner-scripts
---