apiVersion: v1
kind: Service
metadata:
  name: nextcloud-mysql
  labels:
    name: nextcloud-mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    name: nextcloud-mysql
