apiVersion: v1
kind: Service
metadata:
  name: owncloud
  labels:
    name: owncloud
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 80
      protocol: TCP
  selector:
    name: owncloud
