apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    name: nextcloud
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nextcloud
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: 172.16.210.101/public/wonderfall/nextcloud:12.0
    #      args: ["app:nextcloud"]
          env:
            - name: UID
              value: 1000
             - name: GID
              value: 1000
            - name: UPLOAD_MAX_SIZE
              value: 10G
            - name: APC_SHM_SIZE
              value: 128M
            - name: OPCACHE_MEM_SIZE
              value: 128M
            - name:  CRON_PERIOD
              value: 15m
            - name: TZ
              value: Asia/Shanghai
            - name: ADMIN_USER
              value: admin
            - name: ADMIN_PASSWORD
              value: password
            - name: DOMAIN
              value: localhost
            - name: DB_TYPE
              value: mysql
            - name: DB_NAME
              value: nextcloud_db
            - name: DB_USER
              value: nextcloud
            - name: DB_PASSWORD
              value: password
            - name: DB_HOST
              value: nextcloud-mysql

          ports:
            - containerPort: 8888
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: nextdata
          volumeMounts:
            - mountPath: /config
              name: config
          volumeMounts:
            - mountPath: /apps2
              name: apps2
          volumeMounts:
            - mountPath: /nextcloud/themes
              name: themes
          livenessProbe:
            tcpSocket:
              port: 8888
            initialDelaySeconds: 5
            timeoutSeconds: 1
      volumes:
        - name: nextdata
          persistentVolumeClaim:
            claimName: nextcloud-sc-pvc
        - name: config
          persistentVolumeClaim:
            claimName: nextcloud-config-sc-pvc
        - name: apps2
          persistentVolumeClaim:
            claimName: nextcloud-apps2-sc-pvc
        - name: themes
          persistentVolumeClaim:
            claimName: nextcloud-themes-sc-pvc
