apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    name: nextcloud
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nextcloud
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: 172.16.210.101/public/nextcloud:12.0.1-apache
    #      args: ["app:nextcloud"]
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: DEBUG
              value: "false"

            - name: NEXTCLOUD_URL
              value: http://nextcloud.beagledata.com

            - name: NEXTCLOUD_ADMIN_USER
              value: admin
            - name: NEXTCLOUD_ADMIN_PASSWORD
              value: password

            - name: NEXTCLOUD_UPLOAD_MAX_FILESIZE
              value: 8G
            - name: NEXTCLOUD_MAX_FILE_UPLOADS
              value: "1000"

            - name: DB_TYPE
              value: pgsql
            - name: DB_HOST
              value: nextcloud-postgresql
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: nextcloud
            - name: DB_PASS
              value: password
            - name: DB_NAME
              value: nextcloud_db

          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/nextcloud
              name: nextdata
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 1
      volumes:
        - name: nextdata
          persistentVolumeClaim:
            claimName: nextcloud-sc-pvc
