apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nextcloud-postgresql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nextcloud-postgresql
    spec:
      containers:
      - name: nextcloud-postgresql
        image: 172.16.210.101/public/postgres:9.6.3
        env:
          - name: POSTGRES_USER
            value: nextcloud
          - name: POSTGRES_PASSWORD
            value: password
          - name: POSTGRES_DB
            value: nextcloud_db
        ports:
          - containerPort: 5432
            protocol: TCP
        volumeMounts:
          - mountPath: /var/lib/postgresql
            name: pgdata
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 30
          timeoutSeconds: 5
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: nextcloud-pg-sc-pvc
