apiVersion: v1
kind: Service
metadata:
  name: nextcloud-postgresql
  labels:
    name: nextcloud-postgresql
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    name: nextcloud-postgresql
