apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nextcloud-solr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nextcloud-solr
    spec:
      containers:
      - name: nextcloud-solr
        image: 172.16.210.101/public/solr:6-alpine
        imagePullPolicy: IfNotPresent
        command: ['docker-entrypoint.sh']
        args: ["solr-precreate","nextant"]
        ports:
        - name: nextcloud-solr
          containerPort: 8983
        volumeMounts:
        - mountPath: /opt/solr/server/solr/mycores
          name: data
        livenessProbe:
          tcpSocket:
            port: 8983
          initialDelaySeconds: 30
          timeoutSeconds: 5
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nextcloud-solr-sc-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-solr
  labels:
    name: nextcloud-solr
spec:
  selector:
    name: nextcloud-solr
  ports:
    - name: nextcloud-solr
      port: 8983
      targetPort: nextcloud-solr
---