kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: jenkins
  name: jenkins
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: 172.16.210.101/public/jenkins:2.60.2
        #command: ["sleep", "600000"]
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: jenkins-data
          mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-sc-pvc
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: jenkins
  name: jenkins
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: jenkins
