apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kuber-rbd
provisioner: kubernetes.io/rbd
parameters:
  monitors: 172.16.210.121:6789
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: "kube-system"
  pool: kube
  userId: admin
  userSecretName: ceph-secret
 