kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-sc-pvc
  annotations: 
    volume.beta.kubernetes.io/storage-class: kuber-rbd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi