apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mount-pvc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mount-pvc
    spec:
      containers:
      - name: mount-pvc
        image: 172.16.210.101/public/redis:alpine
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /data
          name: data
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: jenkins-sc-pvc
