kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-sc-pvc
  annotations: 
    volume.beta.kubernetes.io/storage-class: kuber-rbd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10000Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-pg-sc-pvc
  annotations: 
    volume.beta.kubernetes.io/storage-class: kuber-rbd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi