apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vim-scp-alpine
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: vim-scp-alpine
    spec:
      containers:
      - name: vim-scp-alpine
        image: 172.16.210.101/public/vim-scp-alpine:latest
        #imagePullPolicy: IfNotPresent
        #command: ["sleep", "600000"]
        ports:
        - name: vim-scp-alpine
          containerPort: 22
        volumeMounts:
        - mountPath: /data
          name: data
        livenessProbe:
          tcpSocket:
            port: 22
          initialDelaySeconds: 30
          timeoutSeconds: 5
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: jenkins-sc-pvc
